
open Student

let decision_consequence_list = [("test", [("end", 0.0)]);
                                 ("single", [("gpa", 0.2)]);
                                 ("double", [("brb", 2.0); ("social_life", 5.0)]);
                                 ("o Week", [("social_life", 5.0); ("health", 3.0)]);
                                 ("stay in", [("social_life",  -2.0); ("health", -2.0)]);
                                 ("look at textbook", [("social_life", -5.0); ("gpa", 0.4)]);
                                 ("leave without them", [("social_life", -3.0); ("morality", -10.0)]);
                                 ("help them home", [("morality", 5.0)]);
                                 ("snooze", [("gpa", -0.5); ("health", 3.0)]);
                                 ("go to class", [("gpa", 0.2); ("health", -2.0); ("social_life", 4.0)]);
                                 ("fun club", [("health", 10.0)]);                       
                                 ("career club", [("gpa", 0.2); ("brbs", 5.0)]);                    
                                 ("charity club", [("morality", 6.0)]);
                                 ("study", [("gpa", 0.2); ("social_life", -5.0)]);
                                 ("go trick or treating", [("gpa", -0.2); ("social_life", 5.0)]);
                                 ("sign up", [("gpa", 0.2); ("social_life", 5.0)]);
                                 ("nah I'm good", [("gpa", -0.2); ("social_life", -5.0); ("health", -3.0)]);
                                 ("do the right thing", [("morality", 10.0)]); 
                                 ("fuck okies", [("morality", -7.0)]);
                                 ("unmask the bear man", [("morality", 10.0)]);
                                 ("make a reddit post about it", [("morality", -7.0); ("social_life", -5.0)]);
                                 ("attend the social", [("social_life", 10.0); ("health", 5.0)]);
                                 ("binge watch youtube", [("health", -5.0); ("social_life", -8.0)]);
                                 ("do some pushups", [("health", 11.0); ("social_life", -8.0)]);
                                 ("lower the course load",[("health", 5.0); ("gpa", 0.3)]);
                                 ("keep current course load", [("health", -5.0); ("social_life", -5.0); ("gpa",-0.2)]);
                                 ("go to dinner", [("health", 7.0); ("social_life", 5.0); ("brbs", -10.0)]);
                                 ("stay home and be lonely", [("health", -5.0); ("social_life", -5.0)]); 
                                 ("sacrifice mental health for gpa", [("health", -8.0); ("gpa", 0.5)]); 
                                 ("fail the assignment", [("health", 8.0); ("gpa", -0.5)]);
                                 ("join the frisbee team", [("health", 10.0); ("social_life", 10.0)]);
                                 ("don't join", [("health", -8.0); ("gpa", 0.3)]);
                                 ("ignore it. It's college", [("morality", 6.0); ("social_life", 4.0)]);
                                 ("report it to the RA", [("morality", -8.0); ("social_life", -9.0)]);
                                 ("get a bike", [("health", 8.0); ("brbs", -10.0); ("gpa", 0.2)]);
                                 ("Keep walking", [("health", 3.0); ("gpa", -0.3)]);
                                 ("start using the bus pass", [("health", -4.0); ("gpa", 0.2)]);
                                 ("Accompany your friend", [("social_life", 5.0); ("health", -2.0)]);
                                 ("Jam out", [("social_life", -5.0); ("health", 2.0)]);
                                 ("Stop and take a pic with touchdown", [("gpa", -0.3); ("social life", 3.0)]);
                                 ("Rush to class", [("gpa", 0.5)]);
                                 ("Cook with roommate", [("social life", 5.0); ("morality", 8.0)]);
                                 ("Onion rings and chicken tenders from Nasties", [("health", -10.0); ("brbs", -10.0)]);
                                 ("Build an igloo", [("social life", 5.0); ("gpa", -0.4)]);
                                 ("Study for prelim", [("gpa", 0.5)]);
                                 ("Netflix and hot chocolate",[("health", 5.0); ("gpa", -0.4)]);
                                 ("Take the sign",[("morality", -5.0); ("health", -5.0)]);
                                 ("Leave it",[("morality", 5.0)]);
                                 ("Put the sign back",[("morality", 5.0)]);
                                 ("Keep going",[("morality", -10.0)]);
                                 ("Visit Denice Cassaro",[("social_life", 2.0)]);
                                 ("Okenshield's",[("health", 3.0)]);
                                 ("watch a movie", ["health", 3.0]);
                                 ("Popcorn",[("health", 10.0)]);
                                 ("Go back home", [("health", 6.0)]);
                                 ("Stay in Ithaca", [("social_life", 8.0)]);
                                 ("Enjoy the great weather",[("gpa", -0.9);("health", 10.0)]);
                                 ("Continue to study",[("gpa", 1.0)]);
                                 ("Rush", [("social_life", 10.0) ]);
                                 ("Don't rush", [("social_life", -3.0)]);
                                 ("Take the bid", [("brbs", -5.0)]);
                                 ("Don't take the bid", [("brbs", 2.5)]);
                                 ("Snuggle up with friends", [("social_life", 1.0)]);
                                 ("Slide down the slope", [("social_life", 1.0); ("health", -1.0)]);
                                 ("Watch lectures", [("gpa", 1.5)]);
                                 ("Talk to a caps counselor", [("health", 2.0)]);
                                 ("binge on junk food and netflix shows", [("health", -1.0)]);
                                 ("hang out with friends", [("social_life", 1.5)]);
                                 ("Go to the career center", [("gpa", 0.2)]);
                                 ("Just apply next year", [("gpa", -0.1)]);
                                 ("Stay on campus", [("gpa", 0.1)]);
                                 ("Go home", [("morality", 4.0)]);
                                 ("Vacation with friends", [("morality", -2.0); ("social_life", 1.0)]);
                                 ("go to the slope", [("social_life", 1.5)]);
                                 ("start studying early", [("gpa", 0.1)]);
                                 ("sleep", [("health", 1.0)]);
                                 ("Sneak it in", [("morality", -3.0)]);
                                 ("Don't sneak it in", [("morality", 3.0)]);
                                 ("Study most of the time", [("gpa", 0.2)]);
                                 ("Mix of friends and books", [("gpa", 0.1); ("social_life", 2.0)]);
                                 ("Don't study at all", [("morality", -3.0)]);
                                 ("Wait around for a seat", [("morality", -1.0)]);
                                 ("Study somewhere else", [("morality", 1.0)]);
                                 ("ice cream class", [("health", -5.0); ("social_life", 7.0)]); ("cs3110", [("health", -3.0); ("social_life", -3.0); ("brbs", 7.0)]);
                                 ("cs 3110",[("social_life", -5.0); ("gpa", 0.2)]);
                                 ("commit",[("gpa", 0.2);("brbs", 5.0)]);
                                 ("later", [("gpa", -0.2)]);
                                 ("get a gym pass",[("brbs", -15.0);("health", 6.0)]);
                                 ("no never going to use it",[("health", -2.0)]);
                                 ("start your homework",[("gpa", 0.3)]);
                                 ("watch the office",[("health", 3.0)]);
                                 ("go to the gym",[("health", 6.0)]);
                                 ("do laundry",[("health", 3.0)]);
                                 ("not career fair",[("gpa", 0.3);("brbs", -5.0)]);
                                 ("career fair",[("brbs", 10.0);("gpa", -0.1)]);
                                 ("big tech company",[("brbs", 5.0)]);
                                 ("small start up",[("brbs", 3.0)]);
                                 ("non profit",[("morality", 10.0)]);
                                 ("help them",[("morality", 7.0);("social_life", 7.0)]);
                                 ("i would never",[("social_life", -4.0); ("morality", 0.5)]);
                                 ("apply to internships",[("brbs", 5.0);("social_life", -2.0);("gpa", -0.1)]);
                                 ("spend time with friends",[("social_life", 3.0);("gpa", -0.1)]);
                                 ("work on homework",[("social_life", -2.0);("gpa", 0.2)]);
                                 ("football game",[("social_life", 3.0);("morality", 2.0)]);
                                 ("cs project",[("social_life", -2.0);("gpa", 0.2)]);
                                 ("canada goose jacket",[("brbs", -10.0)]);
                                 ("jacket from tj maxx",[("brbs", 5.0);]);
                                 ("freeze",[("health", -10.0)]);
                                 ("DING DING!", [("social_life", +5.0);("health", 5.0)]);
                                 ("Stay cozy", [("social_life", -5.0)]);
                                 ("Vote!", [("morality", 5.0)]);
                                 ("What the fuck is a student assembly?", [("morality", -5.0)]);
                                 ("Attend the partner social", [("social_life", 10.0); ("gpa", 0.2)]);
                                 ("I don't need a partner", [("social_life", -5.0); ("gpa", -0.2)]);
                                 ("Wow! I can't believe you've been teaching CS for 58 years!", [("gpa", 0.4)]);
                                 ("Are you sure it's not 56?", [("gpa", -0.2)]);
                                 ("58 years. 58 years. 58 years.", [("gpa", 0.2)]);
                                 ("59 years. 59 years. 59 years.", [("gpa", 0.4)]);
                                 ("Celebrate by throwing a party", [("brbs", -5.0); ("social_life", 5.0)]);
                                 ("Go write some proofs", [("gpa", 0.4); ("social_life", -5.0)]);
                                 ("Give swae his inhaler", [("morality", 10.0); ("social_life", 5.0)]);
                                 ("Meh, Black beatles wasn't that good anyway", [("morality", -10.0)]);
                                 ("Fuck me. I need some substances.", [("gpa", -0.5); ("health", -10.0)]);
                                 ("I'll study super hard and get all As (really tho?)", [("gpa", 0.5); ("health", -10.0)]);
                                 ("Head to collegetown", [("social_life", 10.0); ("health", 12.0); ("morality", 5.0)]);
                                 ("I have no friends. Stay in the low rises.", [("social_life", -10.0); ("health", -6.0); ("morality", -5.0)]);
                                 ("Apply for 1110-3110", [("end", 0.0)]);
                                 ("Meh. I don't remember what I learned", [("end", 0.0)]);
                                ]


let decision_scenario_name = [("single", "Meet Brad");
                              ("double", "Meet Brad");
                              ("o Week", "Roommate and Brad"); 
                              ("o Week", "No Roommate and Brad");
                              ("help them home", "First Day");
                              ("leave without them", "First Day");
                              ("stay in", "First Day");
                              ("look at textbook", "First Day");
                              ("snooze", "Clubfest");
                              ("go to class", "Clubfest");
                              ("fun club", "Halloween");
                              ("test", "ta apps");
                              ("career club", "Halloween");        
                              ("charity club", "Halloween");
                              ("study", "study partner");
                              ("sign up", "stir fry");
                              ("nah I'm good", "stir fry");
                              ("go trick or treating", "stir fry");
                              ("do the right thing", "investigation");
                              ("unmask the bear man", "social event");
                              ("make a reddit post about it", "social event");
                              ("fuck okies", "social event");
                              ("attend the social", "drop");
                              ("binge watch youtube", "drop");
                              ("do some pushups", "drop");
                              ("lower the course load", "dinner out");
                              ("keep current course load", "dinner out");
                              ("go to dinner", "office hours");
                              ("stay home and be lonely", "office hours");
                              ("sacrifice mental health for gpa", "frisbee team");
                              ("fail the assignment", "frisbee team");
                              ("join the frisbee team", "snitching");
                              ("don't join", "snitching");
                              ("ignore it. It's college", "transport");
                              ("report it to the RA", "transport");
                              ("keep walking", "rush");
                              ("start using the bus pass", "rush");
                              ("get a bike", "rush");
                              ("rush", "rush pt 2");
                              ("don't rush", "snow slide");
                              ("take the bid", "snow slide");
                              ("don't take the bid", "snow slide");
                              ("Snuggle up with friends", "igloo");
                              ("slide down the slope", "igloo");
                              ("watch lectures", "igloo");
                              ("build an igloo", "winter sign");
                              ("study for prelim", "winter sign");
                              ("netflix and hot chocolate", "winter sign");
                              ("take the sign", "winter sign fall");
                              ("Leave it", "seasonal depression");
                              ("put the sign back", "seasonal depression");
                              ("keep going", "seasonal depression");
                              ("talk to a caps counselor", "internship");
                              ("binge on junk food and netflix shows", "internship");
                              ("hang out with friends", "internship");
                              ("go to the career center", "touchdown");
                              ("just apply next year", "touchdown");
                              ("stop and take a pic with touchdown", "wsh");
                              ("rush to class", "wsh");
                              ("visit denice cassaro", "nasties run");
                              ("okenshield's", "nasties run");
                              ("watch a movie", "nasties run");
                              ("popcorn", "nasties run"); 
                              ("cook with roommate", "spring break");
                              ("onion rings and chicken tenders from nasties", "spring break");
                              ("stay on campus", "slope day");
                              ("go home", "slope day");
                              ("vacation with friends", "slope day");
                              ("go to the slope", "slope day pt 2");
                              ("start studying early", "ew finals");
                              ("sleep", "ew finals");
                              ("sneak it in", "ew finals");
                              ("don't sneak it in", "ew finals");
                              ("Study most of the time", "Olin finals");
                              ("Mix of friends and books", "Olin finals");
                              ("Don't study at all", "post finals");
                              ("Wait around for a seat", "post finals");
                              ("Study somewhere else", "post finals");
                              ("go back home", "classes");
                              ("stay in ithaca", "classes");
                              ("ice cream class", "Major");
                              ("cs 3110", "Major");
                              ("commit", "Gym Pass"); 
                              ("later", "Gym Pass");
                              ("get a gym pass", "Friday Afternoon");
                              ("no never going to use it", "Friday Afternoon");
                              ("start your homework", "Career Fair Choice"); 
                              ("watch the office", "Career Fair Choice");
                              ("go to the gym", "Career Fair Choice");
                              ("do laundry", "Career Fair Choice");
                              ("career fair", "Career Fair");
                              ("not career fair", "Academic integrity"); 
                              ("big tech company", "Academic integrity"); 
                              ("small start up", "Academic integrity"); 
                              ("non profit", "Academic integrity");
                              ("i would never","applications"); 
                              ("help them","applications");
                              ("apply to internships","Football Game"); 
                              ("spend time with friends","Football Game"); 
                              ("work on homework","Football Game");
                              ("football game","Canada Goose"); 
                              ("cs project","Canada Goose");
                              ("canada goose jacket", "Ring the bell");
                              ("jacket from tj maxx", "Ring the bell");
                              ("freeze", "Ring the bell");
                              ("DING DING!", "SA elections"); 
                              ("Stay cozy", "SA elections");
                              ("Vote!", "Partner Social");
                              ("What the fuck is a student assembly?", "Partner Social");
                              ("Attend the partner social", "57 years");
                              ("I don't a partner", "57 years");
                              ("Wow! I can't believe you've been teaching CS for 58 years!", "God");
                              ("Are you sure it's not 56?", "58 years");
                              ("58 years. 58 years. 58 years.", "inhaler");
                              ("58 years. 58 years. 58 years.", "inhaler");
                              ("Celebrate by throwing a party", "inhaler");
                              ("Go write some proofs", "inhaler");                     
                              ("Give swae his inhaler", "finals sophomore");
                              ("Meh, Black beatles wasn't that good anyway", "finals sophomore");
                              ("Fuck me. I need some substances.", "senior week");
                              ("I'll study super hard and get all As (really tho?)", "senior week");
                              ("Head to collegetown", "Ta apps");
                              ("I have no friends. Stay in the low rises.", "Ta apps");
                              ("Apply for 1110-3110", "end");
                              ("Meh. I don't remember what I learned", "end");
                             ]

let scenario_friends_list = [
  ("DOUBLE", "Sam");
  ("O WEEK", "Brad");
  ("GO TO CLASS", "Jack");
  ("HELP THEM HOME", "Nicola");
  ("FUN CLUB", "Lirinda");
  ("CAREER CLUB", "Maximillian the III");
  ("CHARITY CLUB", "Gandhi");
  ("ATTEND THE SOCIAL", "Sadman");

]